[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/python"]

[[services]]
internal_port = 8000
protocol = "tcp"

[services.http_checks]
path = "/api/health/"

[env]
DEBUG = "False"
